<?php

namespace Gui\Forms\Elements;

use Gui\Forms\Validators\Error;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Collection;
use Illuminate\Support\HtmlString;

class InputCode extends AbstractElement
{
    /**
     * @inheritDoc
     */
    protected function initialize(): void
    {
        parent::initialize();

        $this->addOption('pattern', '/[0-9]/i');
        $this->addOption('template', '###-###');
        $this->addOption('inputmode', 'numeric');
    }

    /**
     * @inheritDoc
     */
    protected function getView(): string
    {
        return 'gui::forms.elements.input-code';
    }

    /**
     * @inheritDoc
     */
    protected function beforeRender(): void
    {
        parent::beforeRender();

        $this->appendAttribute('class', 'gui-control-code');
        $this->setViewVar('componentConfigPattern', $this->getOption('pattern'));
    }

    /**
     * @inheritDoc
     */
    protected function render(string $name, mixed $value = null, ?Error $error = null): string|View
    {
        $this->build($name);
        return parent::render($name, null, $error);
    }

    /**
     * Builds the necessary components based on the provided template and sets them in the view variables.
     *
     * @param string $name The base name to be used for the input fields generated by the template.
     * @return void
     */
    protected function build(string $name): void
    {
        $template = str_split($this->getOption('template'));
        $pieces = new Collection();

        foreach($template as $pieceType){
            if($pieceType === '#'){
                $input = new InputText(attributes: ['maxlength' => 1, 'size' => 1, 'inputmode' => $this->getOption('inputmode'), 'autocomplete' => 'off']);
                $pieces->push($input->toHtml($name . '[]', autoId: false));
            } elseif($pieceType === " "){
                $pieces->push(new HtmlString('<div class="gap"></div>'));
            } else {
                $pieces->push($pieceType);
            }
        }

        $this->setViewVar('pieces', $pieces);
    }
}